Prevent `GetFunctionCodeSigningConfig` calls when a functions packageType is `Image`
aws-controllers-k8s/lambda-controller pull request #21
Opened 2022-01-28 17:15 UTC by A-Hilaly

Issue #, if available:

Description of changes:
Functions code signing config should only be called when a function is
created using an s3bucket and a key. Functions created using a container
image cannot get a code signing configuration.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-28 18:06 UTC, vijtrip2 approved these changes

2022-01-28 18:06 UTC, vijtrip2 commented on pkg/resource/function/hooks.go
> +	if ko.Spec.PackageType != nil && *ko.Spec.PackageType != "Image" {
nit:
```suggestion
	if ko.Spec.PackageType != nil && *ko.Spec.PackageType == "Zip" {
```

2022-01-31 14:27 UTC, jaypipes requested changes
I'd like to see an e2e test added that stresses this code path please! :)

2022-01-31 14:27 UTC, jaypipes commented on pkg/resource/function/hooks.go
>  	}
Consider adding a condition of type [`ACK.Advisory`](https://github.com/aws-controllers-k8s/runtime/blob/d2f3189f3d5b1af4c7093397fef6d8eeb1edc992/apis/core/v1alpha1/conditions.go#L47) in an else block here when the user specifies a code signing configuration for functions with package type != "Zip"...

That would provide the user with some helpful information indicating their desired spec is incorrect.

2022-03-07 16:59 UTC, A-Hilaly commented
>@A-Hilaly where do we stand with this PR? :)

This PR will need more work than expected. We will need proper support for Images based lambda functions (Initializers, custom hooks and proper e2e for it).
Updated #1062

2022-03-18 16:00 UTC, A-Hilaly commented
/hold

2022-03-25 16:24 UTC, A-Hilaly commented
/retest

2022-04-18 16:40 UTC, gagan-eg commented
Do you know the timeline for this to be merged? We switched to using image based Function because currently S3 Key change updates are not supported.

2022-04-26 15:21 UTC, A-Hilaly commented
> Do you know the timeline for this to be merged? We switched to using image based Function because currently S3 Key change updates are not supported.

@gagan-eg very soon :)

2022-04-26 15:21 UTC, A-Hilaly commented
/retest
/unhold

2022-04-26 15:26 UTC, A-Hilaly commented
/test lambda-kind-e2e

2022-04-27 20:37 UTC, vijtrip2 commented on pkg/resource/function/hooks.go
> +	if ko.Spec.PackageType != nil && *ko.Spec.PackageType == "Image" && ko.Spec.CodeSigningConfigARN != nil {
should we add an e2e test for this and assert that terminal condition gets set?

These are good scenarios for unit testing but I believe lambda-controller does not have unit testing right now.

2022-05-02 15:09 UTC, jaypipes commented
@A-Hilaly looking at the failure in the e2e test, I think you need to add terminal codes to the `generator.yaml` so that things like `InvalidParameterValueException` are understood as terminal exceptions....

2022-05-06 16:47 UTC, A-Hilaly commented
/retest

2022-05-06 17:09 UTC, A-Hilaly commented
/retest

2022-05-23 16:19 UTC, jaypipes commented
/lgtm

2022-05-23 16:19 UTC, merged